//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadCompass
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA_VAZAO_RDH
    {
        public System.DateTime data { get; set; }
        public decimal posto { get; set; }
        public Nullable<int> qnat { get; set; }
        public Nullable<double> qinc { get; set; }
        public string fonte { get; set; }
    }
}
